### ISSUE TITLE
Make this repo buildable standalone

### ISSUE THREAD

**Issue by staktrace** [openfare/openfare#2]
Currently checking out this repo and doing a `cargo build` fails because it contains a path dependency to `openfare-js`. Looking at the `openfare-js` code (which is in a sibling repository), that has a path dependency back into this repository. This is not really ideal - either all three (`openfare-lib`, `openfare-js`, and `openfare`) should be in separate repositories using crates.io dependencies, or they should be in the same repository/workspace. I don't recall offhand if you can actually publish to crates.io with path dependencies; I suspect you need to have versioned dependencies for that so it would be better to have that in the Cargo.toml files, and then use `[patch]` in the workspace file to set up the local replacements.

**Comment by rndhouse** [comment]
Thank you once more for taking a look.

At the moment, code changes often span `openfare` and `openfare-lib`. I will keep them in the same repository for now. Once `openfare-lib` becomes more stable I will move it into its own repository.

`openfare-js` changes less often. I've modified it such that it obtains `openfare-lib` from crates.io. I've also modified `openfare` such that it obtains `openfare-js` from crates.io also.

Then I've patched the workspace toml as you've suggested. (Local builds use the same version of `openfare-lib` for `openfare` and `openfare-js`.)

After these changes, it should be simple to setup a dev environment with `git clone` and then `cargo build`.

Please let me know if I've missed anything, or can improve on anything. Feel free to reopen the issue.
