### ISSUE TITLE
Define a minimum supported rust version

### ISSUE THREAD

**Issue by staktrace** [openfare/openfare#3]
It's usually good practice to define a minimum supported rust version for rust projects. Even if it's "whatever the latest rust release is", it would be good to make that explicit. I had rust 1.57.0 on my machine but it doesn't build `openfare-lib` because of the `format!("{payee_name}___{unique_id}")` format strings which are new in 1.58.0.

**Comment by rndhouse** [comment]
Thanks for pointing that out.
I've implemented this fix: https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html#new-format-for-rust-toolchain
